### ISSUE TITLE
mathematical formula display issue

### ISSUE THREAD

**Issue by jianqih** [liao961120/TeXtLite#2]
The mathematical formula couldn't display well using the interline and inline formula using `$$...$$` or `$...$` respectively. Even using the `$$\begin{align/ed}\end{align/ed}$$` couldn't  work.

**Comment by liao961120** [comment]
Do you have `katex: true` set in your post's YAML?

You can take a look at the example post's YAML down below.  
<https://github.com/liao961120/TeXtLite/blob/main/content/post/quarto/index.md>

**Comment by jianqih** [comment]
> Do you have katex: true set in your post's YAML? 
 You can take a look at the example post's YAML down below.
https://github.com/liao961120/TeXtLite/blob/main/content/post/quarto/index.md

Thank you! It works.
